#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE}")"

echo -e "\nrunning all tests...\n"

exit_code=0

for t in test*; do
	echo -e "--- $t ---\n"
	./$t
	[ $? -ne 0 ] && exit_code=1
	echo -e "\n"
done

if [ ${exit_code} -ne 0 ]; then
	echo -e "FAILURE\n"
	exit ${exit_code}
fi

echo -e "SUCCESS\n"
